// Offline self-test of the generated level chunk (luagen) and the pack writer (pack), over synthetic scenes and
// a scratch temp directory only -- no game, no game files. Exit code 0 = all passed.
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

#include "erg/names.h"
#include "erg/pack.h"
#include "erg/patch.h"
#include "erg/scene.h"
#include "levels/manifest.h"
#include "mods/spice.h"

namespace erg = melange::erg;
namespace fs = std::filesystem;
namespace lm = melange::levels::manifest;

namespace {
int g_fail = 0, g_pass = 0;

void Expect(bool ok, const std::string& what) {
    if (ok) {
        ++g_pass;
    } else {
        ++g_fail;
        printf("FAIL: %s\n", what.c_str());
    }
}

erg::Scene BareScene(const std::string& stem) {
    erg::Scene s;
    s.stem = stem;
    s.title = "Test";
    s.base = {"Multi.DinerMight", "game", "Multi_DinerMight", {std::string(64, 'a'), std::string(64, 'b'), std::string(64, 'c')}};
    erg::Frame root;
    root.id = 1;
    root.name = "root";
    s.frames.push_back(root);
    return s;
}

void AddWorm(erg::Scene& s, int i, erg::Vec3 pos) {
    erg::Detail d;
    d.id = 100 + i;
    d.frame = 1;
    d.name = "WORM" + std::to_string(i);
    d.resource = "CheesyGrinWorm";
    d.pos = pos;
    d.role = erg::Role::Spawn;
    s.details.push_back(d);
}

void AddNamed(erg::Scene& s, int64_t id, const char* name, const char* resource) {
    erg::Detail d;
    d.id = id;
    d.frame = 1;
    d.name = name;
    d.resource = resource;
    s.details.push_back(d);
}

// ---- luagen ----------------------------------------------------------------------------------------------------

void TestLuagenEmpty() {
    erg::Scene s = BareScene("demo_empty");
    Expect(!erg::luagen::Needed(s), "an empty scene needs no chunk");
    Expect(erg::luagen::Chunk(s).empty(), "an empty scene's chunk is empty text");
}

void TestLuagenWaterOnly() {
    erg::Scene s = BareScene("demo_water");
    s.water = 40.0;
    Expect(erg::luagen::Needed(s), "a water level needs a chunk");
    const std::string want = "-- generated by Erg for demo_water; edits are overwritten on export\n"
                              "SetData(\"Water.Level\", 40.0000)\n";
    Expect(erg::luagen::Chunk(s) == want, "water-only chunk has just the top-level SetData");
}

void TestLuagenKnotsOnly() {
    erg::Scene s = BareScene("demo_knots");
    s.spawns = erg::SpawnMode::Knots;
    for (int i = 0; i < 8; ++i) AddWorm(s, i, {0, 0, 0});
    const std::string want = "-- generated by Erg for demo_knots; edits are overwritten on export\n"
                              "local ergInit = Initialise\n"
                              "function Initialise()\n"
                              "    local ergSetup = lib_SetupMultiplayerWormsAndTeams\n"
                              "    lib_SetupMultiplayerWormsAndTeams = function()\n"
                              "        ergSetup()\n"
                              "        for i = 0, 7 do\n"
                              "            local lock, worm = EditContainer(lib_GetWormContainerName(i))\n"
                              "            worm.Spawn = \"WORM\" .. i\n"
                              "            CloseContainer(lock)\n"
                              "        end\n"
                              "    end\n"
                              "    ergInit()\n"
                              "    lib_SetupMultiplayerWormsAndTeams = ergSetup\n"
                              "end\n";
    Expect(erg::luagen::Chunk(s) == want, "knots-only chunk has just the loop, no water or PlaceObjects lines");
}

// Knots, two placed objects and a water level together.
void TestLuagenFull() {
    erg::Scene s = BareScene("mymaps_harbour");
    s.title = "Harbour Brawl";
    s.spawns = erg::SpawnMode::Knots;
    s.water = 40.0;
    for (int i = 0; i < 8; ++i) AddWorm(s, i, {0, 0, 0});
    AddNamed(s, 200, "oildrum", "OilDrum");
    AddNamed(s, 201, "mine", "Mine");
    Expect(erg::luagen::Needed(s), "knots + objects + water needs a chunk");
    const std::string want = "-- generated by Erg for mymaps_harbour; edits are overwritten on export\n"
                              "SetData(\"Water.Level\", 40.0000)\n"
                              "local ergInit = Initialise\n"
                              "function Initialise()\n"
                              "    local ergSetup = lib_SetupMultiplayerWormsAndTeams\n"
                              "    lib_SetupMultiplayerWormsAndTeams = function()\n"
                              "        ergSetup()\n"
                              "        for i = 0, 7 do\n"
                              "            local lock, worm = EditContainer(lib_GetWormContainerName(i))\n"
                              "            worm.Spawn = \"WORM\" .. i\n"
                              "            CloseContainer(lock)\n"
                              "        end\n"
                              "        SendMessage(\"GameLogic.PlaceObjects\")\n"
                              "        SetData(\"Water.Level\", 40.0000)\n"
                              "    end\n"
                              "    ergInit()\n"
                              "    lib_SetupMultiplayerWormsAndTeams = ergSetup\n"
                              "end\n";
    Expect(erg::luagen::Chunk(s) == want, "the full chunk matches the expected text byte for byte");
    const std::string legacy = "-- generated by Erg for mymaps_harbour; edits are overwritten on export\n"
                                "SetData(\"Water.Level\", 40.0000)\n"
                                "local ergSetup = lib_SetupMultiplayerWormsAndTeams\n"
                                "function lib_SetupMultiplayerWormsAndTeams()\n"
                                "    ergSetup()\n"
                                "    for i = 0, 7 do\n"
                                "        local lock, worm = EditContainer(lib_GetWormContainerName(i))\n"
                                "        worm.Spawn = \"WORM\" .. i\n"
                                "        CloseContainer(lock)\n"
                                "    end\n"
                                "    SendMessage(\"GameLogic.PlaceObjects\")\n"
                                "    SetData(\"Water.Level\", 40.0000)\n"
                                "end\n";
    std::string run, why;
    Expect(!erg::luagen::IsGenerated(s.stem, legacy, &why) && why.find("older Erg") != std::string::npos,
           "a v1 chunk is not the current form");
    Expect(erg::luagen::Upgrade(s.stem, legacy, &run, &why) && run == want, "a v1 chunk is upgraded to the deferred form on load");
}

void TestLuagenObjectsOnly() {
    erg::Scene s = BareScene("demo_objects");
    AddNamed(s, 200, "mine", "Mine");
    const std::string want = "-- generated by Erg for demo_objects; edits are overwritten on export\n"
                              "local ergInit = Initialise\n"
                              "function Initialise()\n"
                              "    local ergSetup = lib_SetupMultiplayerWormsAndTeams\n"
                              "    lib_SetupMultiplayerWormsAndTeams = function()\n"
                              "        ergSetup()\n"
                              "        SendMessage(\"GameLogic.PlaceObjects\")\n"
                              "    end\n"
                              "    ergInit()\n"
                              "    lib_SetupMultiplayerWormsAndTeams = ergSetup\n"
                              "end\n";
    Expect(erg::luagen::Chunk(s) == want, "objects-only chunk has just PlaceObjects, no knot loop or water");
}

// ---- pack ------------------------------------------------------------------------------------------------------

std::string ReadFile(const fs::path& p) {
    std::ifstream f(p, std::ios::binary);
    if (!f) return "\x01no such file";
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

bool FileExists(const fs::path& p) { return fs::exists(p); }

erg::pack::PackSpec BasicSpec(std::string slug, bool source, bool withChunk) {
    erg::pack::PackSpec spec;
    spec.modId = "erg-pack-test";
    spec.name = "Erg Pack Test";
    spec.version = "1.0.0";
    spec.slug = std::move(slug);
    spec.source = source;
    const std::string stem = "erg_pack_test_" + spec.slug;
    spec.levelFiles = {
        {"assets/levels/" + stem + ".XOM", {'X', 'O', 'M'}},
        {"assets/levels/Maps/" + stem + ".xan", {'X', 'A', 'N'}},
        {"assets/levels/Maps/" + stem + "DAY.csh", {'C', 'S', 'H'}},  // must never be written
    };
    if (withChunk) spec.levelFiles.push_back({"assets/levels/" + stem + ".lub", {'L', 'U', 'B'}});
    spec.patchJson = "{\"format\":\"erg-patch/1\",\"stem\":\"" + stem + "\"}";
    return spec;
}

void TestPackInstall(const fs::path& base) {
    const fs::path dir = base / "install" / "erg-pack-test";
    const auto spec = BasicSpec("sample", /*source=*/false, /*withChunk=*/true);
    std::vector<std::string> files;
    std::string err;
    Expect(erg::pack::WritePack(spec, dir.wstring(), &files, &err), "install export succeeds: " + err);
    Expect(FileExists(dir / "spice.json"), "install writes spice.json");
    Expect(FileExists(dir / "src" / "sample.ergpatch.json"), "install writes the patch");
    Expect(FileExists(dir / "assets" / "levels" / "erg_pack_test_sample.XOM"), "install writes the level XOM");
    Expect(FileExists(dir / "assets" / "levels" / "Maps" / "erg_pack_test_sample.xan"), "install writes the .xan");
    Expect(FileExists(dir / "assets" / "levels" / "erg_pack_test_sample.lub"), "install writes the chunk");
    Expect(!FileExists(dir / "assets" / "levels" / "Maps" / "erg_pack_test_sampleDAY.csh"),
           "install never writes a .csh (hard rule)");
    Expect(!FileExists(dir / "build.ps1"), "install writes no build script");
    const std::string manifest = ReadFile(dir / "spice.json");
    Expect(manifest.find("\"kind\":\"content\"") != std::string::npos, "spice.json is a content mod");
    Expect(manifest.find("\"chunk\":true") != std::string::npos, "spice.json records chunk:true when a .lub ships");
    Expect(manifest.find("\"slug\":\"sample\"") != std::string::npos, "spice.json names the slug");
    melange::spice::Manifest m;
    std::vector<melange::spice::Error> errs;
    Expect(melange::spice::Parse(dir.wstring(), &m, &errs) && errs.empty(),
           "the written spice.json passes the manifest parser" + (errs.empty() ? std::string() : ": " + errs.front().field + " " + errs.front().text));
    Expect(manifest.find("\"survivor\"") == std::string::npos, "no Survivor copy unless asked");
    auto twin = BasicSpec("sample", /*source=*/false, /*withChunk=*/true);
    twin.survivor = true;
    const fs::path dir3 = base / "install-survivor" / "erg-pack-test";
    Expect(erg::pack::WritePack(twin, dir3.wstring(), &files, &err), "install export with a Survivor copy succeeds: " + err);
    melange::spice::Manifest tm;
    errs.clear();
    Expect(melange::spice::Parse(dir3.wstring(), &tm, &errs) && errs.empty() && tm.levels.size() == 1 && tm.levels[0].survivor &&
               tm.levels[0].chunk,
           "spice.json records survivor:true for a Survivor copy");
}

void TestPackSource(const fs::path& base) {
    const fs::path dir = base / "source";
    const auto spec = BasicSpec("sample", /*source=*/true, /*withChunk=*/false);
    std::vector<std::string> files;
    std::string err;
    Expect(erg::pack::WritePack(spec, dir.wstring(), &files, &err), "source export succeeds: " + err);
    Expect(FileExists(dir / "spice.json"), "source writes spice.json");
    Expect(FileExists(dir / "src" / "sample.ergpatch.json"), "source writes the patch");
    Expect(FileExists(dir / "build.ps1"), "source writes build.ps1");
    Expect(FileExists(dir / ".gitignore"), "source writes .gitignore");
    Expect(!FileExists(dir / "assets"), "source ships no assets/levels");
    const std::string manifest = ReadFile(dir / "spice.json");
    Expect(manifest.find("\"chunk\":false") != std::string::npos, "source spice.json records chunk:false (no .lub given)");
    auto withChunk = BasicSpec("sample", /*source=*/true, /*withChunk=*/false);
    withChunk.chunk = true;
    const fs::path dir2 = base / "source-chunk";
    Expect(erg::pack::WritePack(withChunk, dir2.wstring(), &files, &err), "source export with a chunk succeeds: " + err);
    Expect(ReadFile(dir2 / "spice.json").find("\"chunk\":true") != std::string::npos,
           "source spice.json records chunk:true when the built level will have one");
}

void TestPackMerge(const fs::path& base) {
    const fs::path dir = base / "merge";
    std::string err;
    std::vector<std::string> files;
    Expect(erg::pack::WritePack(BasicSpec("first", false, false), dir.wstring(), &files, &err),
           "first level exports: " + err);
    Expect(erg::pack::WritePack(BasicSpec("second", false, false), dir.wstring(), &files, &err),
           "a second level exports into the same folder: " + err);
    const std::string manifest = ReadFile(dir / "spice.json");
    Expect(manifest.find("\"slug\":\"first\"") != std::string::npos, "the first level survives a later export");
    Expect(manifest.find("\"slug\":\"second\"") != std::string::npos, "the second level is added");
    Expect(FileExists(dir / "src" / "first.ergpatch.json") && FileExists(dir / "src" / "second.ergpatch.json"),
           "both patches are on disk");
}

void TestPackSourceMultiLevel(const fs::path& base) {
    const fs::path dir = base / "multi";
    std::string err;
    std::vector<std::string> files;
    for (const char* slug : {"first", "second", "third"})
        Expect(erg::pack::WritePack(BasicSpec(slug, /*source=*/true, /*withChunk=*/false), dir.wstring(), &files, &err),
               std::string("multi-level: ") + slug + " exports: " + err);
    const std::string script = ReadFile(dir / "build.ps1");
    for (const char* slug : {"first", "second", "third"}) {
        const std::string needle = std::string("--patch (Join-Path $root \"src\\") + slug + ".ergpatch.json\")";
        Expect(script.find(needle) != std::string::npos, std::string("multi-level: build.ps1 builds ") + slug);
    }
    size_t n = 0;
    for (size_t pos = script.find("--patch (Join-Path $root"); pos != std::string::npos; pos = script.find("--patch (Join-Path $root", pos + 1)) ++n;
    Expect(n == 3, "multi-level: build.ps1 has one xomtool level build line per level (" + std::to_string(n) + ")");
}

void TestPackRefusesForeignFolder(const fs::path& base) {
    const fs::path dir = base / "foreign";
    fs::create_directories(dir);
    std::ofstream(dir / "spice.json", std::ios::binary)
        << "{\"spiceVersion\":1,\"id\":\"someone-else\",\"version\":\"1.0.0\",\"name\":\"Someone Else\","
           "\"kind\":\"content\",\"weapons\":[{\"name\":\"kWeaponX\",\"base\":\"kWeaponBazooka\",\"cell\":1}]}";
    std::string err;
    std::vector<std::string> files;
    const bool ok = erg::pack::WritePack(BasicSpec("sample", false, false), dir.wstring(), &files, &err);
    Expect(!ok, "a folder with a non-Erg mod (a weapons array) is refused");
    Expect(!err.empty(), "the refusal names a reason");
}

void TestPackStaleAndFolders(const fs::path& base) {
    const fs::path dir = base / "stale" / "erg-pack-test";
    std::string err;
    std::vector<std::string> files;
    auto first = BasicSpec("sample", false, true);
    first.levelFiles.push_back({"assets/levels/Maps/erg_pack_test_sample.hmp", {'H'}});
    first.levelFiles.push_back({"assets/levels/Maps/erg_pack_test_sample.txt", {'T'}});
    Expect(erg::pack::WritePack(first, dir.wstring(), &files, &err), "an export with a .hmp and a chunk succeeds: " + err);
    Expect(FileExists(dir / "assets" / "levels" / "Maps" / "erg_pack_test_sample.hmp"), "the .hmp is written");
    Expect(erg::pack::WritePack(BasicSpec("sample", false, false), dir.wstring(), &files, &err), "a re-export succeeds: " + err);
    Expect(!FileExists(dir / "assets" / "levels" / "Maps" / "erg_pack_test_sample.hmp") &&
               !FileExists(dir / "assets" / "levels" / "Maps" / "erg_pack_test_sample.txt") &&
               !FileExists(dir / "assets" / "levels" / "erg_pack_test_sample.lub"),
           "a re-export without a .hmp, .txt or chunk removes the old ones");
    Expect(ReadFile(dir / "spice.json").find("\"chunk\":false") != std::string::npos, "the re-export records chunk:false");

    const fs::path legacy = base / "legacy";
    fs::create_directories(legacy / "assets" / "Textures");
    std::ofstream(legacy / "assets" / "Textures" / "x.tga", std::ios::binary) << "x";
    Expect(!erg::pack::WritePack(BasicSpec("sample", false, false), legacy.wstring(), &files, &err) &&
               !FileExists(legacy / "spice.json"),
           "a folder with files but no spice.json is refused: " + err);
    const fs::path empty = base / "empty";
    fs::create_directories(empty);
    Expect(erg::pack::WritePack(BasicSpec("sample", false, false), empty.wstring(), &files, &err), "an empty folder is used: " + err);

    const fs::path linked = base / "linked", outside = base / "outside";
    fs::create_directories(linked);
    fs::create_directories(outside);
    const std::wstring cmd = L"cmd /c mklink /J \"" + (linked / "assets").wstring() + L"\" \"" + outside.wstring() + L"\" >nul";
    if (_wsystem(cmd.c_str()) == 0) {
        std::ofstream(linked / "spice.json", std::ios::binary)
            << "{\"spiceVersion\":1,\"id\":\"erg-pack-test\",\"version\":\"1.0.0\",\"name\":\"T\",\"kind\":\"content\"}";
        Expect(!erg::pack::WritePack(BasicSpec("sample", false, false), linked.wstring(), &files, &err) &&
                   fs::is_empty(outside),
               "an export through a junction is refused and writes nothing outside: " + err);
        fs::remove(linked / "assets");
    } else {
        Expect(false, "could not create a junction for the test");
    }
}

void TestPackRefusesBadNames(const fs::path& base) {
    const fs::path dir = base / "badnames";
    std::string err;
    std::vector<std::string> files;
    auto spec = BasicSpec("Sample", false, false);  // uppercase: not a valid slug
    Expect(!erg::pack::WritePack(spec, dir.wstring(), &files, &err), "an invalid slug is refused");
    auto spec2 = BasicSpec("dinermight", false, false);
    spec2.modId = "multi";  // prefix "multi" + slug "dinermight" collides with a vanilla stem
    Expect(!erg::pack::WritePack(spec2, dir.wstring(), &files, &err), "a stem colliding with a vanilla level is refused");
}

// ---- the shipped sample ----------------------------------------------------------------------------------------

std::wstring Widen(const std::string& s) { return std::wstring(s.begin(), s.end()); }

void TestPackScript(const fs::path& base) {
    const std::string text = "wum.log('hello from ' .. wum.level.stem)\n";
    for (bool source : {false, true}) {
        const fs::path dir = base / (source ? "script-source" : "script-install") / "erg-pack-test";
        auto spec = BasicSpec("sample", source, false);
        spec.script = text;
        std::vector<std::string> files;
        std::string err;
        Expect(erg::pack::WritePack(spec, dir.wstring(), &files, &err), "an export with a script succeeds: " + err);
        Expect(ReadFile(dir / "sim" / "sample.lua") == text, "the script is copied to sim/<slug>.lua");
        Expect(std::find(files.begin(), files.end(), "sim/sample.lua") != files.end(), "the written files list the script");
        melange::spice::Manifest m;
        std::vector<melange::spice::Error> errs;
        std::vector<melange::levels::manifest::Error> lerrs;
        const bool parsed = melange::spice::Parse(dir.wstring(), &m, &errs);
        const auto decls = parsed ? melange::levels::manifest::Parse(m, &lerrs) : std::vector<melange::levels::manifest::LevelDecl>{};
        Expect(decls.size() == 1 && decls[0].sim == "sim/sample.lua",
               "spice.json declares levels[].sim" + (errs.empty() ? std::string() : ": " + errs.front().text) +
                   (lerrs.empty() ? std::string() : ": " + lerrs.front().text));
        Expect(erg::pack::WritePack(BasicSpec("sample", source, false), dir.wstring(), &files, &err) &&
                   !FileExists(dir / "sim" / "sample.lua") && ReadFile(dir / "spice.json").find("\"sim\"") == std::string::npos,
               "a re-export without a script removes it: " + err);
    }
    auto bad = BasicSpec("sample", true, false);
    bad.script = std::string("\x1bLua", 4);
    std::vector<std::string> files;
    std::string err;
    Expect(!erg::pack::WritePack(bad, (base / "script-bad").wstring(), &files, &err) && !FileExists(base / "script-bad" / "spice.json"),
           "compiled Lua is refused before anything is written");
}

void TestSampleModParses() {
    const std::wstring dir = Widen(std::string(MELANGE_SOURCE_DIR) + "/dist/Mods/erg-sample");
    melange::spice::Manifest m;
    std::vector<melange::spice::Error> errs;
    const bool ok = melange::spice::Parse(dir, &m, &errs);
    std::string why;
    for (auto& e : errs) why += e.field + ": " + e.text + "; ";
    Expect(ok, "dist/Mods/erg-sample/spice.json parses: " + why);
    if (!ok) return;
    Expect(m.id == "erg-sample", "the sample's id matches its folder name");
    Expect(m.content, "the sample is a content mod");
    Expect(!m.defaultEnabled, "the sample ships disabled");
    Expect(m.levels.size() == 1, "the sample declares exactly one level");
    if (m.levels.size() != 1) return;
    Expect(m.levels[0].slug == "sample", "the level's slug is 'sample'");
    Expect(m.levels[0].chunk, "the level needs a generated chunk (knots + water)");
    Expect(m.levels[0].source == "src/sample.ergpatch.json", "the level names its patch as its source");

    std::vector<lm::Error> lerrs;
    const auto decls = lm::Parse(m, &lerrs);
    Expect(decls.size() == 1 && lerrs.empty(), "the manifest's levels array is accepted by levels::manifest::Parse");
    if (decls.size() == 1) {
        Expect(decls[0].stem == "erg_sample_sample", "the level's stem is erg_sample_sample");
        std::string stemErr;
        Expect(erg::names::ValidStem(decls[0].stem, "erg_sample", &stemErr), "the stem is a valid, non-vanilla stem: " + stemErr);
    }

    const std::string patchText = ReadFile(fs::path(dir) / "src" / "sample.ergpatch.json");
    erg::Patch p;
    std::string perr;
    Expect(erg::ParsePatch(patchText, &p, &perr), "the sample's patch parses: " + perr);
    Expect(p.spawns == erg::SpawnMode::Knots, "the sample uses knot spawns");
    Expect(p.water.has_value() && *p.water == 25.0, "the sample sets water to 25");
    size_t sets = 0, drums = 0, mines = 0, voxels = 0;
    for (auto& op : p.ops) {
        if (op.kind == erg::Op::Kind::Set && op.src >= 1) ++sets;
        if (op.kind == erg::Op::Kind::Add && op.fields.name && *op.fields.name == "oildrum") ++drums;
        if (op.kind == erg::Op::Kind::Add && op.fields.name && *op.fields.name == "mine") ++mines;
        if (op.kind == erg::Op::Kind::Voxels) ++voxels;
    }
    Expect(sets == 8, "the sample moves the 8 knots");
    Expect(drums == 3 && mines == 2, "the sample places 3 drums and 2 mines");
    Expect(voxels > 0 && sets + drums + mines + voxels == p.ops.size(), "the sample carves a little terrain and does nothing else");
}

void TestPackNeverWritesCshEvenIfAskedTwice(const fs::path& base) {
    // Re-running an install export must not resurrect a .csh a previous (buggy) caller left behind.
    const fs::path dir = base / "csh";
    std::string err;
    std::vector<std::string> files;
    Expect(erg::pack::WritePack(BasicSpec("sample", false, true), dir.wstring(), &files, &err), "export ok: " + err);
    for (auto& f : files) Expect(f.size() < 4 || f.substr(f.size() - 4) != ".csh", "no returned file is a .csh: " + f);
}
}  // namespace

int main() {
    TestLuagenEmpty();
    TestLuagenWaterOnly();
    TestLuagenKnotsOnly();
    TestLuagenObjectsOnly();
    TestLuagenFull();

    const fs::path base = fs::temp_directory_path() / "erg_pack_selftest";
    std::error_code ec;
    fs::remove_all(base, ec);
    fs::create_directories(base);
    TestPackInstall(base);
    TestPackSource(base);
    TestPackSourceMultiLevel(base);
    TestPackMerge(base);
    TestPackRefusesForeignFolder(base);
    TestPackRefusesBadNames(base);
    TestPackStaleAndFolders(base);
    TestPackNeverWritesCshEvenIfAskedTwice(base);
    TestPackScript(base);
    fs::remove_all(base, ec);
    TestSampleModParses();

    printf("erg_pack_selftest: %d passed, %d failed\n", g_pass, g_fail);
    return g_fail ? 1 : 0;
}
