// Offline self-test for E: the generated level chunk (luagen) and the pack writer (pack), over synthetic scenes and
// a scratch temp directory only -- no game, no game files. Exit code 0 = all passed.
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

#include "erg/names.h"
#include "erg/pack.h"
#include "erg/patch.h"
#include "erg/scene.h"
#include "levels/manifest.h"
#include "mods/spice.h"

namespace erg = melange::erg;
namespace fs = std::filesystem;
namespace lm = melange::levels::manifest;

namespace {
int g_fail = 0, g_pass = 0;

void Expect(bool ok, const std::string& what) {
    if (ok) {
        ++g_pass;
    } else {
        ++g_fail;
        printf("FAIL: %s\n", what.c_str());
    }
}

erg::Scene BareScene(const std::string& stem) {
    erg::Scene s;
    s.stem = stem;
    s.title = "Test";
    s.base = {"Multi.DinerMight", "game", "Multi_DinerMight", {std::string(64, 'a'), std::string(64, 'b'), std::string(64, 'c')}};
    erg::Frame root;
    root.id = 1;
    root.name = "root";
    s.frames.push_back(root);
    return s;
}

void AddWorm(erg::Scene& s, int i, erg::Vec3 pos) {
    erg::Detail d;
    d.id = 100 + i;
    d.frame = 1;
    d.name = "WORM" + std::to_string(i);
    d.resource = "CheesyGrinWorm";
    d.pos = pos;
    d.role = erg::Role::Spawn;
    s.details.push_back(d);
}

void AddNamed(erg::Scene& s, int64_t id, const char* name, const char* resource) {
    erg::Detail d;
    d.id = id;
    d.frame = 1;
    d.name = name;
    d.resource = resource;
    s.details.push_back(d);
}

// ---- luagen ----------------------------------------------------------------------------------------------------

void TestLuagenEmpty() {
    erg::Scene s = BareScene("m6t_empty");
    Expect(!erg::luagen::Needed(s), "an empty scene needs no chunk");
    Expect(erg::luagen::Chunk(s).empty(), "an empty scene's chunk is empty text");
}

void TestLuagenWaterOnly() {
    erg::Scene s = BareScene("m6t_water");
    s.water = 40.0;
    Expect(erg::luagen::Needed(s), "a water level needs a chunk");
    const std::string want = "-- generated by Erg for m6t_water; edits are overwritten on export\n"
                              "SetData(\"Water.Level\", 40.0000)\n";
    Expect(erg::luagen::Chunk(s) == want, "water-only chunk has just the top-level SetData");
}

void TestLuagenKnotsOnly() {
    erg::Scene s = BareScene("m6t_knots");
    s.spawns = erg::SpawnMode::Knots;
    for (int i = 0; i < 8; ++i) AddWorm(s, i, {0, 0, 0});
    const std::string want = "-- generated by Erg for m6t_knots; edits are overwritten on export\n"
                              "local ergSetup = lib_SetupMultiplayerWormsAndTeams\n"
                              "function lib_SetupMultiplayerWormsAndTeams()\n"
                              "    ergSetup()\n"
                              "    for i = 0, 7 do\n"
                              "        local lock, worm = EditContainer(lib_GetWormContainerName(i))\n"
                              "        worm.Spawn = \"WORM\" .. i\n"
                              "        CloseContainer(lock)\n"
                              "    end\n"
                              "end\n";
    Expect(erg::luagen::Chunk(s) == want, "knots-only chunk has just the loop, no water or PlaceObjects lines");
}

// The spec's own §3.2 example: knots, two placed objects and a water level together.
void TestLuagenFull() {
    erg::Scene s = BareScene("mymaps_harbour");
    s.title = "Harbour Brawl";
    s.spawns = erg::SpawnMode::Knots;
    s.water = 40.0;
    for (int i = 0; i < 8; ++i) AddWorm(s, i, {0, 0, 0});
    AddNamed(s, 200, "oildrum", "OilDrum");
    AddNamed(s, 201, "mine", "Mine");
    Expect(erg::luagen::Needed(s), "knots + objects + water needs a chunk");
    const std::string want = "-- generated by Erg for mymaps_harbour; edits are overwritten on export\n"
                              "SetData(\"Water.Level\", 40.0000)\n"
                              "local ergSetup = lib_SetupMultiplayerWormsAndTeams\n"
                              "function lib_SetupMultiplayerWormsAndTeams()\n"
                              "    ergSetup()\n"
                              "    for i = 0, 7 do\n"
                              "        local lock, worm = EditContainer(lib_GetWormContainerName(i))\n"
                              "        worm.Spawn = \"WORM\" .. i\n"
                              "        CloseContainer(lock)\n"
                              "    end\n"
                              "    SendMessage(\"GameLogic.PlaceObjects\")\n"
                              "    SetData(\"Water.Level\", 40.0000)\n"
                              "end\n";
    Expect(erg::luagen::Chunk(s) == want, "the full chunk matches the design doc's example byte for byte");
}

void TestLuagenObjectsOnly() {
    erg::Scene s = BareScene("m6t_objects");
    AddNamed(s, 200, "mine", "Mine");
    const std::string want = "-- generated by Erg for m6t_objects; edits are overwritten on export\n"
                              "local ergSetup = lib_SetupMultiplayerWormsAndTeams\n"
                              "function lib_SetupMultiplayerWormsAndTeams()\n"
                              "    ergSetup()\n"
                              "    SendMessage(\"GameLogic.PlaceObjects\")\n"
                              "end\n";
    Expect(erg::luagen::Chunk(s) == want, "objects-only chunk has just PlaceObjects, no knot loop or water");
}

// ---- pack ------------------------------------------------------------------------------------------------------

std::string ReadFile(const fs::path& p) {
    std::ifstream f(p, std::ios::binary);
    if (!f) return "\x01no such file";
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

bool FileExists(const fs::path& p) { return fs::exists(p); }

erg::pack::PackSpec BasicSpec(std::string slug, bool source, bool withChunk) {
    erg::pack::PackSpec spec;
    spec.modId = "erg-pack-test";
    spec.name = "Erg Pack Test";
    spec.version = "1.0.0";
    spec.slug = std::move(slug);
    spec.source = source;
    const std::string stem = "erg_pack_test_" + spec.slug;
    spec.levelFiles = {
        {"assets/levels/" + stem + ".XOM", {'X', 'O', 'M'}},
        {"assets/levels/Maps/" + stem + ".xan", {'X', 'A', 'N'}},
        {"assets/levels/Maps/" + stem + "DAY.csh", {'C', 'S', 'H'}},  // must never be written
    };
    if (withChunk) spec.levelFiles.push_back({"assets/levels/" + stem + ".lub", {'L', 'U', 'B'}});
    spec.patchJson = "{\"format\":\"erg-patch/1\",\"stem\":\"" + stem + "\"}";
    return spec;
}

void TestPackInstall(const fs::path& base) {
    const fs::path dir = base / "install" / "erg-pack-test";
    const auto spec = BasicSpec("sample", /*source=*/false, /*withChunk=*/true);
    std::vector<std::string> files;
    std::string err;
    Expect(erg::pack::WritePack(spec, dir.wstring(), &files, &err), "install export succeeds: " + err);
    Expect(FileExists(dir / "spice.json"), "install writes spice.json");
    Expect(FileExists(dir / "src" / "sample.ergpatch.json"), "install writes the patch");
    Expect(FileExists(dir / "assets" / "levels" / "erg_pack_test_sample.XOM"), "install writes the level XOM");
    Expect(FileExists(dir / "assets" / "levels" / "Maps" / "erg_pack_test_sample.xan"), "install writes the .xan");
    Expect(FileExists(dir / "assets" / "levels" / "erg_pack_test_sample.lub"), "install writes the chunk");
    Expect(!FileExists(dir / "assets" / "levels" / "Maps" / "erg_pack_test_sampleDAY.csh"),
           "install never writes a .csh (hard rule)");
    Expect(!FileExists(dir / "build.ps1"), "install writes no build script");
    const std::string manifest = ReadFile(dir / "spice.json");
    Expect(manifest.find("\"kind\":\"content\"") != std::string::npos, "spice.json is a content mod");
    Expect(manifest.find("\"chunk\":true") != std::string::npos, "spice.json records chunk:true when a .lub ships");
    Expect(manifest.find("\"slug\":\"sample\"") != std::string::npos, "spice.json names the slug");
    melange::spice::Manifest m;
    std::vector<melange::spice::Error> errs;
    Expect(melange::spice::Parse(dir.wstring(), &m, &errs) && errs.empty(),
           "the written spice.json passes the manifest parser" + (errs.empty() ? std::string() : ": " + errs.front().field + " " + errs.front().text));
}

void TestPackSource(const fs::path& base) {
    const fs::path dir = base / "source";
    const auto spec = BasicSpec("sample", /*source=*/true, /*withChunk=*/false);
    std::vector<std::string> files;
    std::string err;
    Expect(erg::pack::WritePack(spec, dir.wstring(), &files, &err), "source export succeeds: " + err);
    Expect(FileExists(dir / "spice.json"), "source writes spice.json");
    Expect(FileExists(dir / "src" / "sample.ergpatch.json"), "source writes the patch");
    Expect(FileExists(dir / "build.ps1"), "source writes build.ps1");
    Expect(FileExists(dir / ".gitignore"), "source writes .gitignore");
    Expect(!FileExists(dir / "assets"), "source ships no assets/levels");
    const std::string manifest = ReadFile(dir / "spice.json");
    Expect(manifest.find("\"chunk\":false") != std::string::npos, "source spice.json records chunk:false (no .lub given)");
}

void TestPackMerge(const fs::path& base) {
    const fs::path dir = base / "merge";
    std::string err;
    std::vector<std::string> files;
    Expect(erg::pack::WritePack(BasicSpec("first", false, false), dir.wstring(), &files, &err),
           "first level exports: " + err);
    Expect(erg::pack::WritePack(BasicSpec("second", false, false), dir.wstring(), &files, &err),
           "a second level exports into the same folder: " + err);
    const std::string manifest = ReadFile(dir / "spice.json");
    Expect(manifest.find("\"slug\":\"first\"") != std::string::npos, "the first level survives a later export");
    Expect(manifest.find("\"slug\":\"second\"") != std::string::npos, "the second level is added");
    Expect(FileExists(dir / "src" / "first.ergpatch.json") && FileExists(dir / "src" / "second.ergpatch.json"),
           "both patches are on disk");
}

void TestPackRefusesForeignFolder(const fs::path& base) {
    const fs::path dir = base / "foreign";
    fs::create_directories(dir);
    std::ofstream(dir / "spice.json", std::ios::binary)
        << "{\"spiceVersion\":1,\"id\":\"someone-else\",\"version\":\"1.0.0\",\"name\":\"Someone Else\","
           "\"kind\":\"content\",\"weapons\":[{\"name\":\"kWeaponX\",\"base\":\"kWeaponBazooka\",\"cell\":1}]}";
    std::string err;
    std::vector<std::string> files;
    const bool ok = erg::pack::WritePack(BasicSpec("sample", false, false), dir.wstring(), &files, &err);
    Expect(!ok, "a folder with a non-Erg mod (a weapons array) is refused");
    Expect(!err.empty(), "the refusal names a reason");
}

void TestPackRefusesBadNames(const fs::path& base) {
    const fs::path dir = base / "badnames";
    std::string err;
    std::vector<std::string> files;
    auto spec = BasicSpec("Sample", false, false);  // uppercase: not a valid slug
    Expect(!erg::pack::WritePack(spec, dir.wstring(), &files, &err), "an invalid slug is refused");
    auto spec2 = BasicSpec("dinermight", false, false);
    spec2.modId = "multi";  // prefix "multi" + slug "dinermight" collides with a vanilla stem
    Expect(!erg::pack::WritePack(spec2, dir.wstring(), &files, &err), "a stem colliding with a vanilla level is refused");
}

// ---- the shipped sample (G) ------------------------------------------------------------------------------------

std::wstring Widen(const std::string& s) { return std::wstring(s.begin(), s.end()); }

void TestSampleModParses() {
    const std::wstring dir = Widen(std::string(MELANGE_SOURCE_DIR) + "/dist/Mods/erg-sample");
    melange::spice::Manifest m;
    std::vector<melange::spice::Error> errs;
    const bool ok = melange::spice::Parse(dir, &m, &errs);
    std::string why;
    for (auto& e : errs) why += e.field + ": " + e.text + "; ";
    Expect(ok, "dist/Mods/erg-sample/spice.json parses: " + why);
    if (!ok) return;
    Expect(m.id == "erg-sample", "the sample's id matches its folder name");
    Expect(m.content, "the sample is a content mod");
    Expect(!m.defaultEnabled, "the sample ships disabled");
    Expect(m.levels.size() == 1, "the sample declares exactly one level");
    if (m.levels.size() != 1) return;
    Expect(m.levels[0].slug == "sample", "the level's slug is 'sample'");
    Expect(m.levels[0].chunk, "the level needs a generated chunk (knots + water)");
    Expect(m.levels[0].source == "src/sample.ergpatch.json", "the level names its patch as its source");

    std::vector<lm::Error> lerrs;
    const auto decls = lm::Parse(m, &lerrs);
    Expect(decls.size() == 1 && lerrs.empty(), "the manifest's levels array is accepted by levels::manifest::Parse");
    if (decls.size() == 1) {
        Expect(decls[0].stem == "erg_sample_sample", "the level's stem is erg_sample_sample");
        std::string stemErr;
        Expect(erg::names::ValidStem(decls[0].stem, "erg_sample", &stemErr), "the stem is a valid, non-vanilla stem: " + stemErr);
    }

    const std::string patchText = ReadFile(fs::path(dir) / "src" / "sample.ergpatch.json");
    erg::Patch p;
    std::string perr;
    Expect(erg::ParsePatch(patchText, &p, &perr), "the sample's patch parses: " + perr);
    Expect(p.spawns == erg::SpawnMode::Knots, "the sample uses knot spawns");
    Expect(p.water.has_value() && *p.water == 25.0, "the sample sets water to 25");
    Expect(p.ops.size() == 8, "the sample moves exactly the 8 knots");
    for (auto& op : p.ops) Expect(op.kind == erg::Op::Kind::Set && op.src >= 1, "every op is a plain 'set' on an existing detail");
}

void TestPackNeverWritesCshEvenIfAskedTwice(const fs::path& base) {
    // Re-running an install export must not resurrect a .csh a previous (buggy) caller left behind.
    const fs::path dir = base / "csh";
    std::string err;
    std::vector<std::string> files;
    Expect(erg::pack::WritePack(BasicSpec("sample", false, true), dir.wstring(), &files, &err), "export ok: " + err);
    for (auto& f : files) Expect(f.size() < 4 || f.substr(f.size() - 4) != ".csh", "no returned file is a .csh: " + f);
}
}  // namespace

int main() {
    TestLuagenEmpty();
    TestLuagenWaterOnly();
    TestLuagenKnotsOnly();
    TestLuagenObjectsOnly();
    TestLuagenFull();

    const fs::path base = fs::temp_directory_path() / "erg_pack_selftest";
    std::error_code ec;
    fs::remove_all(base, ec);
    fs::create_directories(base);
    TestPackInstall(base);
    TestPackSource(base);
    TestPackMerge(base);
    TestPackRefusesForeignFolder(base);
    TestPackRefusesBadNames(base);
    TestPackNeverWritesCshEvenIfAskedTwice(base);
    fs::remove_all(base, ec);
    TestSampleModParses();

    printf("erg_pack_selftest: %d passed, %d failed\n", g_pass, g_fail);
    return g_fail ? 1 : 0;
}
