#include "erg/luagen.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>

namespace melange::erg::luagen {
namespace {
constexpr std::string_view kWater = "SetData(\"Water.Level\", ";
constexpr std::string_view kKnotLine = "        worm.Spawn = \"WORM\" .. i\n";
constexpr std::string_view kPlaceLine = "    SendMessage(\"GameLogic.PlaceObjects\")\n";
constexpr std::string_view kCrateCall = "    ergCrate(", kTelepadCall = "    lib_CreateTelepad(", kTriggerCall = "    ergTrigger(";

constexpr std::string_view kCrateFn =
    "local function ergCrate(knot, kind, contents, count, hitpoints, parachute)\n"
    "    SendMessage(\"GameLogic.ResetCrateParameters\")\n"
    "    SetData(\"Crate.Type\", kind)\n"
    "    SetData(\"Crate.Contents\", contents)\n"
    "    SetData(\"Crate.NumContents\", count)\n"
    "    SetData(\"Crate.Spawn\", knot)\n"
    "    SetData(\"Crate.GroundSnap\", 1)\n"
    "    SetData(\"Crate.Parachute\", parachute)\n"
    "    SetData(\"Crate.RandomSpawnPos\", 0)\n"
    "    SetData(\"Crate.Hitpoints\", hitpoints)\n"
    "    SetData(\"Crate.Scale\", 1.0)\n"
    "    SendMessage(\"GameLogic.CreateCrate\")\n"
    "end\n";
constexpr std::string_view kTriggerFn =
    "local function ergTrigger(knot, index, radius, teamCollect, teamDestroy, hitpoints, wormCollect)\n"
    "    SendMessage(\"GameLogic.ResetTriggerParams\")\n"
    "    SetData(\"Trigger.Spawn\", knot)\n"
    "    SetData(\"Trigger.Radius\", radius)\n"
    "    SetData(\"Trigger.Index\", index)\n"
    "    SetData(\"Trigger.TeamCollect\", teamCollect)\n"
    "    SetData(\"Trigger.TeamDestroy\", teamDestroy)\n"
    "    SetData(\"Trigger.HitPoints\", hitpoints)\n"
    "    SetData(\"Trigger.WormCollect\", wormCollect)\n"
    "    SendMessage(\"GameLogic.CreateTrigger\")\n"
    "end\n";

std::string Num(double v) {
    char buf[32];
    snprintf(buf, sizeof buf, "%.4f", v);
    return buf;
}

std::string Quote(std::string_view s) { return "\"" + std::string(s) + "\""; }

bool HasNamedDetail(const Scene& s, std::string_view name) {
    for (auto& d : s.details)
        if (d.name == name) return true;
    return false;
}

bool Fail(std::string* why, std::string text) {
    if (why) *why = std::move(text);
    return false;
}

std::string Header(std::string_view stem) {
    return "-- generated by Erg for " + std::string(stem) + "; edits are overwritten on export\n";
}

std::optional<double> WaterIn(std::string_view text) {
    const size_t at = text.find(kWater);
    if (at == std::string_view::npos) return std::nullopt;
    const size_t start = at + kWater.size(), end = text.find(')', start);
    if (end == std::string_view::npos || end - start > 24) return std::nullopt;
    const std::string num(text.substr(start, end - start));
    char* stop = nullptr;
    const double v = std::strtod(num.c_str(), &stop);
    if (!stop || *stop || !std::isfinite(v)) return std::nullopt;
    return v;
}

// Emitted lines never hold a literal the parser could not read back, so only well-formed objects are written.
std::string ObjectLine(const ObjectSpec& o) {
    switch (o.type) {
        case ObjectType::Crate: {
            const bool health = o.crate.kind == CrateKind::Health;
            return std::string(kCrateCall) + Quote(o.knot) + ", " + Quote(CrateKindName(o.crate.kind)) + ", " +
                   Quote(health ? "health" : o.crate.contents) + ", " + std::to_string(health ? o.crate.amount : o.crate.count) +
                   ", " + std::to_string(o.crate.hitpoints) + ", " + (o.crate.parachute ? "1" : "0") + ")\n";
        }
        case ObjectType::Telepad: return std::string(kTelepadCall) + Quote(o.knot) + ", " + std::to_string(o.group) + ")\n";
        case ObjectType::Trigger: {
            const TriggerSpec& t = o.trigger;
            return std::string(kTriggerCall) + Quote(o.knot) + ", " + std::to_string(t.index) + ", " + Num(t.radius) + ", " +
                   std::to_string(t.teamCollect) + ", " + std::to_string(t.teamDestroy) + ", " + std::to_string(t.hitpoints) +
                   ", " + (t.wormCollect ? "1" : "0") + ")\n";
        }
        case ObjectType::MineFactory: return {};
    }
    return {};
}

// Splits "a, b, c" of a call's argument list; strings are "..." without escapes.
bool SplitArgs(std::string_view s, std::vector<std::string_view>* out) {
    size_t i = 0;
    while (i <= s.size()) {
        size_t j = s.find(", ", i);
        if (j == std::string_view::npos) j = s.size();
        if (j == i) return false;
        out->push_back(s.substr(i, j - i));
        if (j == s.size()) break;
        i = j + 2;
    }
    return !out->empty();
}

bool StrArg(std::string_view a, std::string* out) {
    if (a.size() < 2 || a.front() != '"' || a.back() != '"') return false;
    *out = std::string(a.substr(1, a.size() - 2));
    return out->find_first_of("\"\\\n") == std::string::npos;
}

bool IntArg(std::string_view a, int* out) {
    if (a.empty() || a.size() > 6) return false;
    int v = 0;
    for (char c : a) {
        if (c < '0' || c > '9') return false;
        v = v * 10 + (c - '0');
    }
    *out = v;
    return true;
}

bool NumArg(std::string_view a, double* out) {
    if (a.empty() || a.size() > 24) return false;
    const std::string n(a);
    char* stop = nullptr;
    *out = std::strtod(n.c_str(), &stop);
    return stop && !*stop && std::isfinite(*out);
}

bool ParseObjectLine(std::string_view line, ObjectSpec* o) {
    std::string_view call;
    ObjectType type;
    if (line.starts_with(kCrateCall)) call = line.substr(kCrateCall.size()), type = ObjectType::Crate;
    else if (line.starts_with(kTelepadCall)) call = line.substr(kTelepadCall.size()), type = ObjectType::Telepad;
    else if (line.starts_with(kTriggerCall)) call = line.substr(kTriggerCall.size()), type = ObjectType::Trigger;
    else return false;
    if (call.empty() || call.back() != ')') return false;
    std::vector<std::string_view> a;
    if (!SplitArgs(call.substr(0, call.size() - 1), &a)) return false;
    o->type = type;
    if (!StrArg(a[0], &o->knot)) return false;
    switch (type) {
        case ObjectType::Crate: {
            std::string kind, contents;
            int n = 0, parachute = 0;
            if (a.size() != 6 || !StrArg(a[1], &kind) || !ParseCrateKind(kind, &o->crate.kind) || !StrArg(a[2], &contents) ||
                !IntArg(a[3], &n) || !IntArg(a[4], &o->crate.hitpoints) || !IntArg(a[5], &parachute) || parachute > 1)
                return false;
            o->crate.parachute = parachute == 1;
            if (o->crate.kind == CrateKind::Health) {
                if (contents != "health") return false;
                o->crate.amount = n;
            } else {
                o->crate.contents = contents;
                o->crate.count = n;
            }
            break;
        }
        case ObjectType::Telepad:
            if (a.size() != 2 || !IntArg(a[1], &o->group)) return false;
            break;
        case ObjectType::Trigger: {
            TriggerSpec& t = o->trigger;
            int worm = 0;
            if (a.size() != 7 || !IntArg(a[1], &t.index) || !NumArg(a[2], &t.radius) || !IntArg(a[3], &t.teamCollect) ||
                !IntArg(a[4], &t.teamDestroy) || !IntArg(a[5], &t.hitpoints) || !IntArg(a[6], &worm) || worm > 1)
                return false;
            t.wormCollect = worm == 1;
            break;
        }
        case ObjectType::MineFactory: return false;
    }
    return ValidateObject(*o, "object", nullptr);
}
}  // namespace

ChunkSpec SpecOf(const Scene& s) {
    ChunkSpec c;
    c.knots = s.spawns == SpawnMode::Knots;
    c.placeObjects = HasNamedDetail(s, "mine") || HasNamedDetail(s, "oildrum");
    c.objects = s.objects;
    c.water = s.water;
    return c;
}

bool Needed(const Scene& s) {
    const ChunkSpec c = SpecOf(s);
    return c.knots || c.placeObjects || !c.objects.empty() || c.water.has_value();
}

std::string Chunk(const Scene& s) {
    if (!Needed(s)) return {};
    return Text(s.stem, SpecOf(s));
}

std::string Text(std::string_view stem, const ChunkSpec& c) {
    if (!c.knots && !c.placeObjects && c.objects.empty() && !c.water) return {};
    bool crates = false, triggers = false;
    for (auto& o : c.objects) {
        if (o.type == ObjectType::MineFactory || !ValidateObject(o, "object", nullptr)) return {};
        crates |= o.type == ObjectType::Crate;
        triggers |= o.type == ObjectType::Trigger;
    }
    std::string out = Header(stem);
    if (c.water) out += std::string(kWater) + Num(*c.water) + ")\n";
    if (c.knots || c.placeObjects || !c.objects.empty()) {
        if (crates) out += kCrateFn;
        if (triggers) out += kTriggerFn;
        out += "local ergSetup = lib_SetupMultiplayerWormsAndTeams\n";
        out += "function lib_SetupMultiplayerWormsAndTeams()\n";
        out += "    ergSetup()\n";
        if (c.knots) {
            out += "    for i = 0, 7 do\n";
            out += "        local lock, worm = EditContainer(lib_GetWormContainerName(i))\n";
            out += kKnotLine;
            out += "        CloseContainer(lock)\n";
            out += "    end\n";
        }
        if (c.placeObjects) out += kPlaceLine;
        for (auto& o : c.objects) out += ObjectLine(o);
        if (c.water) out += "    " + std::string(kWater) + Num(*c.water) + ")\n";
        out += "end\n";
    }
    if (out.size() > kMaxChunkBytes) return {};
    return out;
}

std::string Text(std::string_view stem, bool knots, bool objects, std::optional<double> water) {
    ChunkSpec c;
    c.knots = knots;
    c.placeObjects = objects;
    c.water = water;
    return Text(stem, c);
}

std::string Stub(std::string_view stem) { return "-- generated by Erg for " + std::string(stem) + "; no changes\n"; }

bool Parse(std::string_view stem, std::string_view text, ChunkSpec* out) {
    if (!text.starts_with(Header(stem))) return false;
    ChunkSpec c;
    c.water = WaterIn(text);
    c.knots = text.find(kKnotLine) != std::string_view::npos;
    c.placeObjects = text.find(kPlaceLine) != std::string_view::npos;
    size_t i = 0;
    while (i < text.size()) {
        size_t e = text.find('\n', i);
        if (e == std::string_view::npos) e = text.size();
        const std::string_view line = text.substr(i, e - i);
        if (line.starts_with(kCrateCall) || line.starts_with(kTelepadCall) || line.starts_with(kTriggerCall)) {
            if (c.objects.size() >= kMaxObjects) return false;
            ObjectSpec o;
            if (!ParseObjectLine(line, &o)) return false;
            c.objects.push_back(std::move(o));
        }
        i = e + 1;
    }
    *out = std::move(c);
    return true;
}

bool IsGenerated(std::string_view stem, std::string_view text, std::string* why) {
    if (!text.empty() && static_cast<unsigned char>(text.front()) == 0x1B) return Fail(why, "is compiled Lua, which is refused");
    if (text.empty() || text.size() > kMaxChunkBytes) return Fail(why, "is not a chunk generated by Erg");
    if (text == Stub(stem)) return true;
    ChunkSpec c;
    if (Parse(stem, text, &c)) {
        const std::string want = Text(stem, c);
        if (!want.empty() && want == text) return true;
    }
    return Fail(why, "is not a chunk generated by Erg (hand edits are not run)");
}
}  // namespace melange::erg::luagen
