#include "erg/luagen.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>

namespace melange::erg::luagen {
namespace {
constexpr std::string_view kWater = "SetData(\"Water.Level\", ";

std::string Num(double v) {
    char buf[32];
    snprintf(buf, sizeof buf, "%.4f", v);
    return buf;
}

bool HasNamedDetail(const Scene& s, std::string_view name) {
    for (auto& d : s.details)
        if (d.name == name) return true;
    return false;
}

bool Fail(std::string* why, std::string text) {
    if (why) *why = std::move(text);
    return false;
}

std::optional<double> WaterIn(std::string_view text) {
    const size_t at = text.find(kWater);
    if (at == std::string_view::npos) return std::nullopt;
    const size_t start = at + kWater.size(), end = text.find(')', start);
    if (end == std::string_view::npos || end - start > 24) return std::nullopt;
    const std::string num(text.substr(start, end - start));
    char* stop = nullptr;
    const double v = std::strtod(num.c_str(), &stop);
    if (!stop || *stop || !std::isfinite(v)) return std::nullopt;
    return v;
}
}  // namespace

bool Needed(const Scene& s) {
    return s.spawns == SpawnMode::Knots || s.water.has_value() || HasNamedDetail(s, "mine") ||
           HasNamedDetail(s, "oildrum");
}

std::string Chunk(const Scene& s) {
    if (!Needed(s)) return {};
    return Text(s.stem, s.spawns == SpawnMode::Knots, HasNamedDetail(s, "mine") || HasNamedDetail(s, "oildrum"), s.water);
}

std::string Text(std::string_view stem, bool knots, bool objects, std::optional<double> water) {
    if (!knots && !objects && !water) return {};
    std::string out = "-- generated by Erg for " + std::string(stem) + "; edits are overwritten on export\n";
    if (water) out += std::string(kWater) + Num(*water) + ")\n";
    if (knots || objects) {
        out += "local ergSetup = lib_SetupMultiplayerWormsAndTeams\n";
        out += "function lib_SetupMultiplayerWormsAndTeams()\n";
        out += "    ergSetup()\n";
        if (knots) {
            out += "    for i = 0, 7 do\n";
            out += "        local lock, worm = EditContainer(lib_GetWormContainerName(i))\n";
            out += "        worm.Spawn = \"WORM\" .. i\n";
            out += "        CloseContainer(lock)\n";
            out += "    end\n";
        }
        if (objects) out += "    SendMessage(\"GameLogic.PlaceObjects\")\n";
        if (water) out += "    " + std::string(kWater) + Num(*water) + ")\n";
        out += "end\n";
    }
    return out;
}

std::string Stub(std::string_view stem) { return "-- generated by Erg for " + std::string(stem) + "; no changes\n"; }

bool IsGenerated(std::string_view stem, std::string_view text, std::string* why) {
    if (!text.empty() && static_cast<unsigned char>(text.front()) == 0x1B) return Fail(why, "is compiled Lua, which is refused");
    if (text.empty() || text.size() > kMaxChunkBytes) return Fail(why, "is not a chunk generated by Erg");
    if (text == Stub(stem)) return true;
    const std::optional<double> water = WaterIn(text);
    for (int k = 0; k < 2; ++k)
        for (int o = 0; o < 2; ++o)
            for (int w = 0; w < 2; ++w) {
                if (w && !water) continue;
                const std::string want = Text(stem, k != 0, o != 0, w ? water : std::nullopt);
                if (!want.empty() && want == text) return true;
            }
    return Fail(why, "is not a chunk generated by Erg (hand edits are not run)");
}
}  // namespace melange::erg::luagen
