#!/usr/bin/env python3
"""
gen_cpp_schema.py - turn tools/xom/schema.json into src/xom/xom_schema.inc for
the C++ library (so the C++ side has no JSON dependency).

    python gen_cpp_schema.py [schema.json] [out.inc]
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, HERE)
import xom  # noqa: E402  (MATH_FMT is the single source of truth for math layouts)

TYPE_ENUM = {
    'bool': 'Bool', 'u8': 'U8', 'i8': 'I8', 'u16': 'U16', 'i16': 'I16', 'u32': 'U32', 'i32': 'I32',
    'u64': 'U64', 'i64': 'I64', 'f32': 'F32', 'f64': 'F64', 'enum': 'Enum',
    'bitfield32': 'Bitfield32', 'bitfield64': 'Bitfield64', 'string': 'String', 'ref': 'Ref',
    'pointer': 'Pointer', 'interface': 'Interface', 'void': 'Void',
}


def math_spec(fmt):
    n = ''.join(c for c in fmt if c.isdigit())
    return fmt[-1], int(n) if n else 1


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'schema.json')
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(REPO, 'src', 'xom', 'xom_schema.inc')
    s = json.load(open(src))
    classes = s['classes']
    names = sorted(classes)
    if 'XContainer' not in classes:
        names = ['XContainer'] + names
        classes['XContainer'] = dict(parent=None, guid='', fields=[])
    idx = {n: i for i, n in enumerate(names)}
    maths = sorted(xom.MATH_FMT)
    midx = {n: i for i, n in enumerate(maths)}
    L = ['// Generated by tools/xom/gen_cpp_schema.py from tools/xom/schema.json. Do not edit.',
         '// clang-format off', '']
    L.append('static const MathDef kMath[] = {')
    for m in maths:
        c, n = math_spec(xom.MATH_FMT[m])
        L.append('  {"%s", \'%s\', %d},' % (m, c, n))
    L.append('};')
    L.append('')
    L.append('static const FieldDef kFields[] = {')
    first = {}
    k = 0
    for n in names:
        first[n] = k
        for f in classes[n]['fields']:
            a = f.get('attrs', {})
            sf = int(a.get('Schema', {}).get('FromVersion', -1))
            of = int(a.get('Obsolete', {}).get('FromVersion', -1))
            t = f['type']
            if t in TYPE_ENUM:
                ty, mi = 'Type::' + TYPE_ENUM[t], 0
            else:
                ty, mi = 'Type::Math', midx[t]
            L.append('  {"%s", %s, %d, 0x%02x, %d, %d},' % (f['name'], ty, mi, f['flags'], sf, of))
            k += 1
    if k == 0:
        L.append('  {"", Type::Void, 0, 0, -1, -1},')
    L.append('};')
    L.append('')
    L.append('static const ClassDef kClasses[] = {')
    for n in names:
        c = classes[n]
        p = idx.get(c.get('parent'), -1) if c.get('parent') else -1
        L.append('  {"%s", "%s", %d, %d, %d},' % (n, c.get('guid') or '', p, first[n], len(c['fields'])))
    L.append('};')
    L.append('')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w', newline='\n') as fh:
        fh.write('\n'.join(L))
    print('wrote %s: %d classes, %d fields, %d math types' % (out, len(names), k, len(maths)))


if __name__ == '__main__':
    main()
