#!/usr/bin/env python3
"""
weapons_report.py - render Data/Tweak/WEAPTWK.XOM as docs/data/weapons.md.

    python weapons_report.py [WEAPTWK.XOM] [out.md]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import xom  # noqa: E402

DEFAULT_IN = r'C:\Program Files (x86)\Steam\steamapps\common\WormsXHD\Data\Tweak\WEAPTWK.XOM'
DEFAULT_OUT = os.path.normpath(os.path.join(HERE, '..', '..', 'docs', 'data', 'weapons.md'))


def fmt(v):
    if isinstance(v, float):
        s = '%.6g' % v
        return s
    if isinstance(v, bool):
        return 'yes' if v else 'no'
    if isinstance(v, dict) and 'ref' in v:
        return '#%d' % v['ref']
    if isinstance(v, list):
        return '[' + ', '.join(fmt(x) for x in v) + ']'
    if isinstance(v, str):
        return '`%s`' % v if v else ''
    return str(v)


def is_default(v):
    return v in (0, 0.0, False, '', None, []) or (isinstance(v, list) and all(x in (0, 0.0, '') for x in v))


def cell(f, k):
    v = f.get(k)
    if v is None:
        return ''
    if k == 'LifeTime' and v == -1:
        return 'none'
    return fmt(v)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_IN
    out = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT
    doc = xom.load(src, strict=True)
    bank = xom.obj(doc, doc['root'])
    assert bank['type'] == 'XDataBank'
    F = bank['fields']

    # name -> container via the bank's XContainerResourceDetails entries
    named = []
    for r in F['ContainerResources']:
        rd = xom.obj(doc, r)['fields']
        named.append((rd['Name'], rd['Flags'], rd['Value']['ref'], xom.obj(doc, rd['Value'])))

    L = []
    w = L.append
    w('# Weapon data (WEAPTWK.XOM)')
    w('')
    w('Generated by `tools/xom/weapons_report.py` from the retail `Data/Tweak/WEAPTWK.XOM` '
      '(build #1077) with the `tools/xom` reader. Do not edit by hand; rerun the script.')
    w('')
    w('How the file is organised [V]: the root object is an `XDataBank`. Its `ContainerResources` '
      'list holds one `XContainerResourceDetails` per weapon, named after the weapon id '
      '(`kWeaponBazooka`, ...) and pointing at the weapon\'s property container. The class of '
      'that container decides the field set: `BaseWeaponContainer` (utilities and scripted '
      'weapons), `PayloadWeaponPropertiesContainer` (anything that launches a projectile) and its '
      'subclasses `Jumping`/`Homing`/`Flying` (sheep, homing missile, super sheep/starburst), '
      '`GunWeaponPropertiesContainer`, `MeleeWeaponPropertiesContainer` and '
      '`SentryGunWeaponPropertiesContainer`. The bank\'s scalar resources (`Int`/`Uint`/`Float`/'
      '`String`/`Vector`/`Color`) are global tuning keys such as `Bomber.NumBombs`.')
    w('')
    w('Units [I, from names and value ranges]: times are milliseconds (`LifeTime` = fuse, -1 = no '
      'fuse); distances and radii are world units (a worm is about 15 units tall, see '
      '`Worm.EyeLevelOffset`); damage is hit points; `ImpulseMagnitude` and speeds are per-ms '
      'physics units. `WeaponType` is a raw `EnumTypeInfo` value (u32); its name table has not '
      'been decoded, and it does not map cleanly onto a weapon category (Dynamite is 5 like the '
      'melee weapons, Sheep 8, Old Woman and Scouser 9, air strikes and Concrete Donkey 10).')
    w('')
    w('`Flags` is the bank entry\'s `XResourceDetails.Flags` (0x50 or 0x51 here; scalar keys use 0x40). '
      'The meaning of bit 0 is not decoded: it is set on most panel weapons but also clear on some '
      '(Sniper Rifle, Starburst, Sentry Gun, Poison Arrow).')
    w('')

    payload = [n for n in named if 'Payload' in n[3]['type']]
    w('## Projectile weapons (`PayloadWeaponPropertiesContainer` and subclasses)')
    w('')
    cols = [('Damage', 'WormDamageMagnitude'), ('Dmg radius', 'WormDamageRadius'),
            ('Land radius', 'LandDamageRadius'), ('Impulse', 'ImpulseMagnitude'),
            ('Impulse radius', 'ImpulseRadius'), ('Fuse ms', 'LifeTime'),
            ('Bomblets', 'NumBomblets'), ('Bomblet weapon', 'BombletWeaponName'),
            ('Strike bombs', 'NumStrikeBombs'), ('Payload model', 'PayloadGraphicsResourceID'),
            ('Held model', 'WeaponGraphicsResourceID'), ('Detonation FX', 'DetonationFx'),
            ('Display name', 'DisplayName')]
    w('| Id | Obj | Class | Flags | Type | ' + ' | '.join(c for c, _ in cols) + ' |')
    w('|' + '---|' * (5 + len(cols)))
    for name, flags, ref, o in payload:
        f = o['fields']
        cls = o['type'].replace('PayloadWeaponPropertiesContainer', 'Payload')
        w('| `%s` | #%d | %s | %d | %s | ' % (name, ref, cls, flags, f.get('WeaponType')) +
          ' | '.join(cell(f, k) for _, k in cols) + ' |')
    w('')

    w('## Guns, melee and sentry gun')
    w('')
    cols2 = [('Damage', 'WormDamageMagnitude'), ('Dmg radius', 'WormDamageRadius'),
             ('Land dmg', 'LandDamageMagnitude'), ('Land radius', 'LandDamageRadius'),
             ('Impulse', 'ImpulseMagnitude'), ('Impulse radius', 'ImpulseRadius'),
             ('Bullets', 'NumberOfBullets'), ('Accuracy', 'Accuracy'), ('Range', 'Range'),
             ('Melee radius', 'Radius'), ('Held model', 'WeaponGraphicsResourceID'),
             ('Display name', 'DisplayName')]
    w('| Id | Obj | Class | Flags | Type | ' + ' | '.join(c for c, _ in cols2) + ' |')
    w('|' + '---|' * (5 + len(cols2)))
    for name, flags, ref, o in named:
        if o['type'] not in ('GunWeaponPropertiesContainer', 'MeleeWeaponPropertiesContainer',
                             'SentryGunWeaponPropertiesContainer'):
            continue
        f = o['fields']
        cls = o['type'].replace('WeaponPropertiesContainer', '')
        w('| `%s` | #%d | %s | %d | %s | ' % (name, ref, cls, flags, f.get('WeaponType')) +
          ' | '.join(cell(f, k) for _, k in cols2) + ' |')
    w('')
    w('Sentry gun shots use `ShotWormDamageMagnitude`/`ShotWormDamageRadius` (see its detail section).')
    w('')

    w('## Utilities and scripted weapons (`BaseWeaponContainer`)')
    w('')
    w('These carry only the common fields (display name, held model, animations, delays); their '
      'behaviour is hard-coded or scripted, plus the global keys below.')
    w('')
    w('| Id | Obj | Flags | Type | Held model | Display name | Launch delay | Post-launch delay |')
    w('|---|---|---|---|---|---|---|---|')
    for name, flags, ref, o in named:
        if o['type'] != 'BaseWeaponContainer':
            continue
        f = o['fields']
        w('| `%s` | #%d | %d | %s | %s | %s | %s | %s |' % (
            name, ref, flags, f['WeaponType'], cell(f, 'WeaponGraphicsResourceID'),
            cell(f, 'DisplayName'), f['LaunchDelay'], f['PostLaunchDelay']))
    w('')

    w('## Other containers in the bank')
    w('')
    for name, flags, ref, o in named:
        if o['type'].endswith('WeaponContainer') or 'WeaponPropertiesContainer' in o['type']:
            continue
        w('- `%s` (#%d, %s): %s' % (name, ref, o['type'], ', '.join(
            '%s=%s' % (k, fmt(v)) for k, v in o['fields'].items())))
    w('')

    w('## Global tuning keys (bank scalar resources)')
    w('')
    w('| Key | Kind | Value |')
    w('|---|---|---|')
    for lst, kind in (('IntResources', 'int'), ('UintResources', 'uint'), ('FloatResources', 'float'),
                      ('StringResources', 'string'), ('VectorResources', 'vector'),
                      ('ColorResources', 'color')):
        for r in F[lst]:
            rd = xom.obj(doc, r)['fields']
            w('| `%s` | %s | %s |' % (rd['Name'], kind, fmt(rd['Value'])))
    w('')

    w('## Per-weapon detail')
    w('')
    w('All fields of each weapon container in stream order, omitting zero / empty / false values. '
      'Field names are the engine\'s own schema names (`tools/xom/schema.json`).')
    w('')
    for name, flags, ref, o in named:
        f = o['fields']
        w('### %s' % name)
        w('')
        w('%s, object #%d. ' % (o['type'], ref) + ', '.join(
            '%s=%s' % (k, fmt(v)) for k, v in f.items() if not is_default(v) or k == 'WeaponType'))
        w('')

    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(L))
    print('wrote', out, '(%d weapons/containers)' % len(named))


if __name__ == '__main__':
    main()
