#pragma once
#include <string>
#include <vector>

#include "import/state.h"
#include "store/install.h"

// Putting generated packs in place: the previous packs move to old\, the staged ones into Mods\, all or nothing,
// with a journal so a crash halfway is undone at the next start. Only folders whose spice.json says
// generated.by == <plugin> are ever moved or removed.
namespace melange::import {
using store::install::MoveFn;

bool IsGeneratedBy(const std::wstring& dir, const std::string& plugin);
// Mods\<plugin>-<1..9> that exist; `foreign` gets the ones not generated by the plugin.
std::vector<std::string> ExistingPacks(const Paths& p, const std::string& plugin, std::vector<std::string>* foreign);

// Moves `staged` (folders under stageRoot named by pack id) into Mods\, replacing every existing generated pack of
// the plugin. On failure everything is moved back and *err says why. Leaves the journal marked committed on success;
// call Finish() once the state is written.
bool Place(const Paths& p, const std::string& plugin, const std::wstring& stageRoot, const std::vector<std::string>& staged,
           std::string* err, const MoveFn& mv = store::install::DefaultMove);
void Finish(const Paths& p);
// At start: undo an uncommitted placement, clean a committed one. False when an old pack could not be moved back.
bool Recover(const Paths& p, const std::string& plugin, const MoveFn& mv = store::install::DefaultMove);
// Removes every generated pack of the plugin; returns their ids, or false with *err when one could not be moved.
bool RemovePacks(const Paths& p, const std::string& plugin, std::vector<std::string>* removed, std::string* err,
                 const MoveFn& mv = store::install::DefaultMove);
}  // namespace melange::import
